---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
locale: en-US
title_separator: "-"
name: Berk Dülger
description: An ordinary web blog
url: https://berkdulger.github.io
baseurl:
teaser: skyscrapers_blue_sky-wallpaper-1920x1080.jpg
gh_repo:
words_per_minute: 200
comments:
  provider:
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:
analytics:
  provider: false
  google:
    tracking_id:
google_ad_client:
google_ad_slot:
author:
  name: Berk Dülger
  avatar: bio-photo.png
  bio: Software Consulant addicted to high quality engineering. DevOps enthusiast. Dad to be
  location: Istanbul, Turkey
  email: berk_dulger@yahoo.com.tr
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: berkdulger
  google_plus:
  keybase:
  instagram:
  lastfm:
  lastfm:
  linkedin: berkdulger
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter:
  vine:
  weibo:
  xing:
  youtube:
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true